import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const FIREBASE_SDK_VERSION = "10.13.2";

const REQUIRED_KEYS = [
    "VITE_FIREBASE_API_KEY",
    "VITE_FIREBASE_AUTH_DOMAIN",
    "VITE_FIREBASE_PROJECT_ID",
    "VITE_FIREBASE_STORAGE_BUCKET",
    "VITE_FIREBASE_MESSAGING_SENDER_ID",
    "VITE_FIREBASE_APP_ID"
];

function readEnvValues(env) {
    return {
        apiKey: env.VITE_FIREBASE_API_KEY?.trim() || "",
        authDomain: env.VITE_FIREBASE_AUTH_DOMAIN?.trim() || "",
        projectId: env.VITE_FIREBASE_PROJECT_ID?.trim() || "",
        storageBucket:
            env.VITE_FIREBASE_STORAGE_BUCKET?.trim() ||
            "matayehuda.firebasestorage.app",
        messagingSenderId:
            env.VITE_FIREBASE_MESSAGING_SENDER_ID?.trim() || "",
        appId: env.VITE_FIREBASE_APP_ID?.trim() || ""
    };
}

export function getMissingFirebaseSwEnvKeys(env) {
    return REQUIRED_KEYS.filter((key) => !env[key]?.trim());
}

export function buildFirebaseMessagingSwSource(config) {
    return `/* eslint-disable no-undef */
/* Auto-generated by scripts/generateFirebaseMessagingSw.js — do not edit manually */
importScripts(
    "https://www.gstatic.com/firebasejs/${FIREBASE_SDK_VERSION}/firebase-app-compat.js"
);
importScripts(
    "https://www.gstatic.com/firebasejs/${FIREBASE_SDK_VERSION}/firebase-messaging-compat.js"
);

firebase.initializeApp({
    apiKey: ${JSON.stringify(config.apiKey)},
    authDomain: ${JSON.stringify(config.authDomain)},
    projectId: ${JSON.stringify(config.projectId)},
    storageBucket: ${JSON.stringify(config.storageBucket)},
    messagingSenderId: ${JSON.stringify(config.messagingSenderId)},
    appId: ${JSON.stringify(config.appId)}
});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
    console.info("[fcm-sw] Background message received", payload);

    const title =
        payload.notification?.title ||
        payload.data?.title ||
        "מטה יהודה";
    const body =
        payload.notification?.body || payload.data?.body || "";

    self.registration.showNotification(title, {
        body,
        icon: "/favicon.svg",
        data: payload.data || {}
    });
});

self.addEventListener("notificationclick", (event) => {
    event.notification.close();
    event.waitUntil(clients.openWindow(event.notification.data?.link || "/"));
});
`;
}

export function generateFirebaseMessagingSw(env, {
    outputPath = resolve(process.cwd(), "public/firebase-messaging-sw.js"),
    logPrefix = "[fcm-sw]"
} = {}) {
    const missing = getMissingFirebaseSwEnvKeys(env);

    if (missing.length > 0) {
        console.warn(
            `${logPrefix} Skipping service worker generation; missing env: ${missing.join(", ")}`
        );
        return { ok: false, missing };
    }

    const config = readEnvValues(env);
    const source = buildFirebaseMessagingSwSource(config);

    writeFileSync(outputPath, source, "utf8");

    console.info(`${logPrefix} Generated ${outputPath}`, {
        projectId: config.projectId,
        messagingSenderId: config.messagingSenderId,
        appId: config.appId
    });

    return { ok: true, config };
}
